server:
  port: 8082
eureka:
  instance:
    status-page-url-path: /admin/info
    health-check-url-path: /admin/health
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: hello-service
