server:
  port: 8082
eureka:
  instance:
    status-page-url-path: /admin/info
    health-check-url-path: /admin/health
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: hello-service

  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root